-- Migration: add abstention & match strength audit columns to recommendation_log
-- Safe to run multiple times (uses IF NOT EXISTS)
-- Generated by Phase 4 audit log fix

ALTER TABLE recommendation_log
    ADD COLUMN IF NOT EXISTS abstained         BOOLEAN     DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS abstain_reason    TEXT        DEFAULT '',
    ADD COLUMN IF NOT EXISTS top_match_strength REAL       DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS closest_matches_codes JSONB   DEFAULT '[]'::jsonb;

-- Index for quick analytics on abstained rows
CREATE INDEX IF NOT EXISTS idx_rec_log_abstained ON recommendation_log (abstained);
CREATE INDEX IF NOT EXISTS idx_rec_log_ms        ON recommendation_log (top_match_strength);

COMMENT ON COLUMN recommendation_log.abstained IS 'True when the pipeline decided not to return recommendations (no confident match)';
COMMENT ON COLUMN recommendation_log.abstain_reason IS 'Human-readable reason for abstention';
COMMENT ON COLUMN recommendation_log.top_match_strength IS 'Absolute BM25+coverage match strength of top candidate (0-1)';
COMMENT ON COLUMN recommendation_log.closest_matches_codes IS 'JSON array of IS codes that were closest matches when abstained';
